const catalog = [
    {
        "id": "ba1",
        "title": "База Lorem1",
        "subgroup": "БAЗЫ",
        "new": true,
        "hit": false,
        "imgSrc": "CAD",
        "price": "500",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "ba1"   
    },
    {
        "id": "ba2",
        "title": "База Lorem2",
        "subgroup": "БAЗЫ",
        "new": false,
        "hit": false,
        "imgSrc": "CAD",
        "price": "500",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "ba2"   
    },
    {
        "id": "ba3",
        "title": "База Lorem3",
        "subgroup": "БAЗЫ",
        "new": false,
        "hit": false,
        "imgSrc": "CAD",
        "price": "500",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "ba3"   
    },
    {
        "id": "ba4",
        "title": "База Lorem4",
        "subgroup": "БAЗЫ",
        "new": false,
        "hit": false,
        "imgSrc": "CAD",
        "price": "500",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "ba4"   
    },
    {
        "id": "ba5",
        "title": "База Lorem5",
        "subgroup": "БAЗЫ",
        "new": false,
        "hit": true,
        "imgSrc": "CAD",
        "price": "500",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "ba5"   
    },
    {
        "id": "tp1",
        "title": "Топ Lorem1",
        "subgroup": "ТОПЫ",
        "new": true,
        "hit": false,
        "imgSrc": "CAD",
        "price": "300",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "tp1"    
    },
    {
        "id": "tp2",
        "title": "Топ Lorem2",
        "subgroup": "ТОПЫ",
        "new": false,
        "hit": true,
        "imgSrc": "CAD",
        "price": "300",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "tp2"    
    },
    {
        "id": "tp3",
        "title": "Топ Lorem3",
        "subgroup": "ТОПЫ",
        "new": false,
        "hit": false,
        "imgSrc": "CAD",
        "price": "300",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "tp3"    
    },
    {
        "id": "tp4",
        "title": "Топ Lorem4",
        "subgroup": "ТОПЫ",
        "new": false,
        "hit": true,
        "imgSrc": "CAD",
        "price": "300",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "tp4"    
    },
    {
        "id": "tp5",
        "title": "Топ Lorem5",
        "subgroup": "ТОПЫ",
        "new": false,
        "hit": false,
        "imgSrc": "CAD",
        "price": "300",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "tp5"    
    },
    {
        "id": "gl1",
        "title": "Гель-лак Lorem1",
        "subgroup": "ГЕЛЬ-ЛАКИ",
        "new": true,
        "hit": false,
        "imgSrc": "CAD",
        "price": "400",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "gl1"    
    },
    {
        "id": "gl2",
        "title": "Гель-лак Lorem2",
        "subgroup": "ГЕЛЬ-ЛАКИ",
        "new": false,
        "hit": false,
        "imgSrc": "CAD",
        "price": "400",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "gl2"  
    },  
    {
        "id": "gl3",
        "title": "Гель-лак Lorem3",
        "subgroup": "ГЕЛЬ-ЛАКИ",
        "new": false,
        "hit": false,
        "imgSrc": "CAD",
        "price": "400",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "gl3"    
    },
    {
        "id": "gl4",
        "title": "Гель-лак Lorem4",
        "subgroup": "ГЕЛЬ-ЛАКИ",
        "new": false,
        "hit": false,
        "imgSrc": "CAD",
        "price": "400",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "gl4"    
    },
    {
        "id": "gl5",
        "title": "Гель-лак Lorem5",
        "subgroup": "ГЕЛЬ-ЛАКИ",
        "new": false,
        "hit": false,
        "imgSrc": "CAD",
        "price": "400",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "gl5"    
    },
    {
        "id": "gk1",
        "title": "Гель-краска Lorem1",
        "subgroup": "ГЕЛЬ-КРАСКИ",
        "new": true,
        "hit": true,
        "imgSrc": "CAD",
        "price": "500",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "gk1"   
    },
    {
        "id": "gk2",
        "title": "Гель-краска Lorem2",
        "subgroup": "ГЕЛЬ-КРАСКИ",
        "new": false,
        "hit": false,
        "imgSrc": "CAD",
        "price": "500",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "gk2"   
    },
    {
        "id": "gk3",
        "title": "Гель-краска Lorem3",
        "subgroup": "ГЕЛЬ-КРАСКИ",
        "new": false,
        "hit": false,
        "imgSrc": "CAD",
        "price": "500",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "gk3"   
    },
    {
        "id": "gk4",
        "title": "Гель-краска Lorem4",
        "subgroup": "ГЕЛЬ-КРАСКИ",
        "new": false,
        "hit": false,
        "imgSrc": "CAD",
        "price": "500",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "gk4"   
    },
    {
        "id": "gk5",
        "title": "Гель-краска Lorem5",
        "subgroup": "ГЕЛЬ-КРАСКИ",
        "new": false,
        "hit": false,
        "imgSrc": "CAD",
        "price": "500",
        "size": "30",
        "description": "Описание продукта, его преимущества",
        "application": "Как приминять продукт при работе",
        "structure": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "article": "gk5"   
    }
]

module.exports = catalog;